# permissions for end users to edit tags.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: tag-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: test-operator
    app.kubernetes.io/part-of: test-operator
    app.kubernetes.io/managed-by: kustomize
  name: tag-editor-role
rules:
- apiGroups:
  - uptimekuma.aleix.cloud
  resources:
  - tags
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - uptimekuma.aleix.cloud
  resources:
  - tags/status
  verbs:
  - get
